import React, { useState } from "react";
import "./styles.css";

// ---- MOCK DATA (Backend + Sui + AI entegrasyonu gelince burayı doldurursun) ----

const PAGES = {
  AGENT: "agent",
  COINS: "coins",
  NFTS: "nfts",
  STAKING: "staking",
  HISTORY: "history",
  WALLET: "wallet",
};

const MOCK_COINS = [
  {
    symbol: "SUI",
    name: "Sui",
    price: 0.89,
    change24h: +2.3,
    sparkline: [30, 40, 45, 38, 50, 60, 55],
  },
  {
    symbol: "BTC",
    name: "Bitcoin",
    price: 95000,
    change24h: -1.2,
    sparkline: [60, 58, 55, 57, 59, 61, 60],
  },
  {
    symbol: "ETH",
    name: "Ethereum",
    price: 4200,
    change24h: +0.7,
    sparkline: [35, 37, 39, 40, 42, 41, 43],
  },
  {
    symbol: "USDC",
    name: "USD Coin",
    price: 1,
    change24h: 0.0,
    sparkline: [48, 50, 49, 51, 50, 49, 50],
  },
];

const INITIAL_NFTS = [
  {
    id: 1,
    name: "Sui Voyager #001",
    description: "Genesis explorer of the Sui network.",
    prompt: "retro neon space voyager",
    imageUrl: "https://placehold.co/400x400/0f172a/9ca3af?text=Voyager+001",
    staked: true,
    apy: 18,
  },
  {
    id: 2,
    name: "Flow Orb #023",
    description: "Dynamic orb reacting to on-chain activity.",
    prompt: "minimal glowing orb",
    imageUrl: "https://placehold.co/400x400/020617/60a5fa?text=Orb+023",
    staked: false,
    apy: 14,
  },
];

const MOCK_HISTORY = [
  {
    id: "tx_01",
    type: "SWAP",
    asset: "SUI → USDC",
    amount: "100 SUI",
    status: "Success",
    time: "2025-12-05 21:14",
    viaAgent: true,
    promptSummary: "Swap 100 SUI to USDC at best price.",
  },
  {
    id: "tx_02",
    type: "MINT_NFT",
    asset: "Sui Voyager #001",
    amount: "1 NFT",
    status: "Success",
    time: "2025-12-04 18:03",
    viaAgent: true,
    promptSummary: "Create a neon space pilot NFT.",
  },
  {
    id: "tx_03",
    type: "STAKE",
    asset: "Sui Voyager #001",
    amount: "1 NFT",
    status: "Pending",
    time: "2025-12-03 11:52",
    viaAgent: false,
    promptSummary: "Stake NFT for yield.",
  },
];

// ---- APP ROOT ----

function App() {
  const [activePage, setActivePage] = useState(PAGES.AGENT);
  const [wallet, setWallet] = useState({
    connected: false,
    address: "",
    suiBalance: 0,
  });
  const [coins] = useState(MOCK_COINS);
  const [nfts, setNfts] = useState(INITIAL_NFTS);
  const [history, setHistory] = useState(MOCK_HISTORY);

  const handleConnectWallet = () => {
    if (!wallet.connected) {
      // TODO: Burayı gerçek Sui / Slash wallet entegrasyonu ile değiştir
      setWallet({
        connected: true,
        address: "0x42a1...9fD3",
        suiBalance: 248.73,
      });
    } else {
      setWallet({ connected: false, address: "", suiBalance: 0 });
    }
  };

  const handleToggleStake = (nftId) => {
    setNfts((prev) =>
      prev.map((nft) =>
        nft.id === nftId ? { ...nft, staked: !nft.staked } : nft
      )
    );
  };

  const handleCreateNftFromPrompt = (promptText) => {
    if (!promptText.trim()) return;

    const id = Date.now();
    const newNft = {
      id,
      name: `AI Mint #${id.toString().slice(-4)}`,
      description: "Generated by your AI agent command.",
      prompt: promptText,
      imageUrl: `https://placehold.co/400x400/111827/4ade80?text=AI+Mint`,
      staked: false,
      apy: 12,
    };

    setNfts((prev) => [newNft, ...prev]);
    setHistory((prev) => [
      {
        id: `tx_${id}`,
        type: "MINT_NFT",
        asset: newNft.name,
        amount: "1 NFT",
        status: "Success",
        time: new Date().toISOString().slice(0, 16).replace("T", " "),
        viaAgent: true,
        promptSummary: promptText.slice(0, 80),
      },
      ...prev,
    ]);
  };

  return (
    <div className="app-root">
      <Sidebar activePage={activePage} onChangePage={setActivePage} />

      <div className="app-main">
        <Topbar wallet={wallet} onConnectWallet={handleConnectWallet} />

        <div className="app-content">
          {activePage === PAGES.AGENT && (
            <AgentPage coins={coins} />
          )}
          {activePage === PAGES.COINS && (
            <CoinsPage coins={coins} />
          )}
          {activePage === PAGES.NFTS && (
            <NftsPage
              nfts={nfts}
              onCreateNftFromPrompt={handleCreateNftFromPrompt}
            />
          )}
          {activePage === PAGES.STAKING && (
            <StakingPage nfts={nfts} onToggleStake={handleToggleStake} />
          )}
          {activePage === PAGES.HISTORY && (
            <HistoryPage history={history} />
          )}
          {activePage === PAGES.WALLET && (
            <WalletPage wallet={wallet} coins={coins} />
          )}
        </div>
      </div>
    </div>
  );
}

// ---- LAYOUT COMPONENTS ----

function Sidebar({ activePage, onChangePage }) {
  const items = [
    { key: PAGES.AGENT, label: "AI Agent", icon: "🤖" },
    { key: PAGES.COINS, label: "Coins", icon: "📊" },
    { key: PAGES.NFTS, label: "NFTs", icon: "🖼️" },
    { key: PAGES.STAKING, label: "Staking", icon: "📥" },
    { key: PAGES.HISTORY, label: "History", icon: "📜" },
    { key: PAGES.WALLET, label: "Wallet", icon: "👛" },
  ];

  return (
    <aside className="sidebar">
      <div className="sidebar-logo">
        <span className="sidebar-logo-mark">S</span>
        <div className="sidebar-logo-text">
          <span>Sui Agent</span>
          <small>AI Transaction Hub</small>
        </div>
      </div>

      <nav className="sidebar-nav">
        {items.map((item) => (
          <button
            key={item.key}
            className={
              "sidebar-nav-item" +
              (activePage === item.key ? " sidebar-nav-item--active" : "")
            }
            onClick={() => onChangePage(item.key)}
          >
            <span className="sidebar-nav-icon">{item.icon}</span>
            <span>{item.label}</span>
          </button>
        ))}
      </nav>

      <div className="sidebar-footer">
        <span className="sidebar-badge">Sui • Dev / Test</span>
      </div>
    </aside>
  );
}

function Topbar({ wallet, onConnectWallet }) {
  return (
    <header className="topbar">
      <div className="topbar-left">
        <h1 className="topbar-title">AI-Powered Sui Console</h1>
        <p className="topbar-subtitle">
          Give natural language commands. Let your agent handle the on-chain work.
        </p>
      </div>
      <div className="topbar-right">
        <div className="topbar-network">
          <span className="network-dot" />
          <span className="network-label">Sui Network</span>
        </div>
        <div className="topbar-wallet">
          {wallet.connected ? (
            <>
              <div className="wallet-info">
                <span className="wallet-address">
                  {wallet.address}
                </span>
                <span className="wallet-balance">
                  {wallet.suiBalance.toFixed(2)} SUI
                </span>
              </div>
              <button
                className="btn btn-ghost"
                onClick={onConnectWallet}
              >
                Disconnect
              </button>
            </>
          ) : (
            <button
              className="btn btn-primary"
              onClick={onConnectWallet}
            >
              Connect Wallet
            </button>
          )}
        </div>
      </div>
    </header>
  );
}

// ---- PAGE: AI AGENT (MAIN) ----

function StatsCard({ label, value, sublabel, trend }) {
  return (
    <div className="stats-card">
      <div className="stats-label">{label}</div>
      <div className="stats-main-row">
        <span className="stats-value">{value}</span>
        {trend && <span className="stats-trend">{trend}</span>}
      </div>
      {sublabel && <div className="stats-sublabel">{sublabel}</div>}
    </div>
  );
}

function AgentPage({ coins }) {
  const [messages, setMessages] = useState([
    {
      id: 1,
      from: "agent",
      text: "Welcome! Tell me what you want to do on Sui. For example: “Swap 50 SUI to USDC and send it to my cold wallet.”",
      time: "now",
    },
  ]);
  const [input, setInput] = useState("");
  const [selectedCoin, setSelectedCoin] = useState(null);

  const sendMessage = () => {
    if (!input.trim()) return;

    const userMessage = {
      id: Date.now(),
      from: "user",
      text: input.trim(),
      time: "now",
    };

    const mockAgentReply = {
      id: Date.now() + 1,
      from: "agent",
      text:
        "Got it. I will translate this into Sui transactions. (Here you will call your backend / AI agent API.)",
      time: "now",
    };

    setMessages((prev) => [...prev, userMessage, mockAgentReply]);
    setInput("");
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  return (
    <div className="agent-page">
      {/* ÜST İSTATİSTİK KARTLARI */}
      <div className="agent-stats-row">
        <StatsCard
          label="Wallet balance"
          value="248.73 SUI"
          sublabel="Connected Sui wallet"
          trend="+5.5% today"
        />
        <StatsCard
          label="AI transactions"
          value="32"
          sublabel="Last 24h via agent"
          trend="+12%"
        />
        <StatsCard
          label="NFTs"
          value="14"
          sublabel="Owned on Sui"
          trend="+3 new"
        />
        <StatsCard
          label="Staked value"
          value="$4,230"
          sublabel="Estimated"
          trend="+2.1%"
        />
      </div>

      {/* ALT GRID: SOLDa CHAT, SAĞDA MARKET WATCH */}
      <div className="agent-grid">
        <div
          className={
            "agent-main" + (selectedCoin ? " agent-main--with-chart" : "")
          }
        >
          <div className="agent-chat-panel">
            <div className="agent-chat-header">
              <h2>Command your on-chain AI agent</h2>
              <p>
                Describe what you want. The agent will build Sui transactions
                (swaps, NFT mints, staking, transfers) from your prompt.
              </p>
            </div>
            <div className="agent-chat-messages">
              {messages.map((msg) => (
                <div
                  key={msg.id}
                  className={
                    "chat-bubble chat-bubble--" +
                    (msg.from === "user" ? "user" : "agent")
                  }
                >
                  <div className="chat-bubble-meta">
                    <span className="chat-bubble-from">
                      {msg.from === "user" ? "You" : "Agent"}
                    </span>
                    <span className="chat-bubble-time">{msg.time}</span>
                  </div>
                  <p className="chat-bubble-text">{msg.text}</p>
                </div>
              ))}
            </div>
            <div className="agent-chat-input">
              <textarea
                placeholder='Example: "Swap 100 SUI to USDC and send to 0xabc... in one transaction."'
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={handleKeyDown}
              />
              <button className="btn btn-primary" onClick={sendMessage}>
                Send to Agent
              </button>
            </div>
          </div>

          {selectedCoin && (
            <div className="agent-chart-column">
              <CoinChart coin={selectedCoin} />
            </div>
          )}
        </div>

        <div className="agent-side">
          <div className="agent-side-header">
            <h3>Market watch</h3>
            <p>Live snapshot of the assets your agent can use.</p>
          </div>
          <CoinList coins={coins} onSelect={setSelectedCoin} />
        </div>
      </div>
    </div>
  );
}

// ---- SHARED: COIN LIST + CHART ----

function CoinList({ coins, onSelect }) {
  return (
    <div className="coin-list">
      {coins.map((coin) => (
        <button
          key={coin.symbol}
          className="coin-row"
          onClick={() => onSelect(coin)}
        >
          <div className="coin-row-left">
            <div className="coin-avatar">
              {coin.symbol[0]}
            </div>
            <div>
              <div className="coin-name">
                {coin.name} ({coin.symbol})
              </div>
              <div className="coin-price">
                ${coin.price.toLocaleString()}
              </div>
            </div>
          </div>
          <div className="coin-row-right">
            <span
              className={
                "coin-change " +
                (coin.change24h >= 0 ? "coin-change--up" : "coin-change--down")
              }
            >
              {coin.change24h >= 0 ? "+" : ""}
              {coin.change24h}%
            </span>
          </div>
        </button>
      ))}
    </div>
  );
}

function CoinChart({ coin }) {
  const data = coin.sparkline || [30, 40, 35, 45, 50, 55, 60];

  return (
    <div className="coin-chart">
      <div className="coin-chart-header">
        <h3>
          {coin.name} ({coin.symbol})
        </h3>
        <div className="coin-chart-price-line">
          <span className="coin-chart-price">
            ${coin.price.toLocaleString()}
          </span>
          <span
            className={
              "coin-change " +
              (coin.change24h >= 0 ? "coin-change--up" : "coin-change--down")
            }
          >
            {coin.change24h >= 0 ? "+" : ""}
            {coin.change24h}% (24h)
          </span>
        </div>
        <p className="coin-chart-caption">
          Simple inline sparkline for now. Here you can plug TradingView,
          custom charts, or Sui on-chain data.
        </p>
      </div>
      <div className="coin-chart-body">
        {data.map((v, i) => (
          <div
            key={i}
            className="coin-chart-bar"
            style={{ height: `${v}%` }}
          />
        ))}
      </div>
      <div className="coin-chart-footer">
        <span>1h</span>
        <span>4h</span>
        <span>1d</span>
        <span>1w</span>
      </div>
    </div>
  );
}

// ---- PAGE: COINS ----

function CoinsPage({ coins }) {
  return (
    <div className="page">
      <div className="page-header">
        <h2>Tracked coins</h2>
        <p>
          View the assets your AI agent can use. This page is read-only: no
          manual buy/sell, only monitoring.
        </p>
      </div>
      <div className="page-card">
        <table className="table">
          <thead>
            <tr>
              <th>Asset</th>
              <th>Price</th>
              <th>24h</th>
              <th>Notes</th>
            </tr>
          </thead>
          <tbody>
            {coins.map((coin) => (
              <tr key={coin.symbol}>
                <td>
                  <div className="table-asset">
                    <div className="coin-avatar small">
                      {coin.symbol[0]}
                    </div>
                    <span>
                      {coin.name} ({coin.symbol})
                    </span>
                  </div>
                </td>
                <td>${coin.price.toLocaleString()}</td>
                <td>
                  <span
                    className={
                      "coin-change " +
                      (coin.change24h >= 0
                        ? "coin-change--up"
                        : "coin-change--down")
                    }
                  >
                    {coin.change24h >= 0 ? "+" : ""}
                    {coin.change24h}%
                  </span>
                </td>
                <td>
                  Used for agent swaps / transfers on Sui (configure in
                  backend).
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// ---- PAGE: NFTS ----

function NftsPage({ nfts, onCreateNftFromPrompt }) {
  const [prompt, setPrompt] = useState("");

  const handleCreate = () => {
    onCreateNftFromPrompt(prompt);
    setPrompt("");
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleCreate();
    }
  };

  return (
    <div className="page">
      <div className="page-header">
        <h2>Your NFTs</h2>
        <p>
          Ask the AI agent to design and mint NFTs on Sui. This UI sends the
          description; your backend + agent handle minting.
        </p>
      </div>

      <div className="page-card nft-creator">
        <h3>Describe the NFT you want</h3>
        <p>
          The more specific you are, the better the result. You can also add
          traits, rarity, collection rules, etc.
        </p>
        <textarea
          className="nft-prompt-input"
          placeholder='Example: "Minimal cyberpunk pilot in blue, full-body, neon Sui logo in the background."'
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          onKeyDown={handleKeyDown}
        />
        <div className="nft-creator-actions">
          <button
            className="btn btn-primary"
            onClick={handleCreate}
          >
            Ask Agent to Mint
          </button>
          <span className="helper-text">
            In production: this will trigger your AI + mint smart contract.
          </span>
        </div>
      </div>

      <div className="nft-grid">
        {nfts.map((nft) => (
          <div key={nft.id} className="nft-card">
            <div className="nft-image-wrapper">
              <img src={nft.imageUrl} alt={nft.name} />
            </div>
            <div className="nft-body">
              <h3>{nft.name}</h3>
              <p className="nft-desc">{nft.description}</p>
              <p className="nft-prompt">
                <span>Prompt:</span> {nft.prompt}
              </p>
            </div>
            <div className="nft-footer">
              <span className="nft-apy">{nft.apy}% APY (if staked)</span>
              {nft.staked && (
                <span className="badge badge-success">Staked</span>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ---- PAGE: STAKING ----

function StakingPage({ nfts, onToggleStake }) {
  const stakeable = nfts.filter((n) => !n.staked);
  const staked = nfts.filter((n) => n.staked);

  return (
    <div className="page">
      <div className="page-header">
        <h2>NFT Staking</h2>
        <p>
          Stake / unstake NFTs via your AI agent or directly from this UI
          (frontend-only toggle here; real logic lives on-chain).
        </p>
      </div>

      <div className="staking-layout">
        <div className="page-card staking-column">
          <h3>Available to stake</h3>
          {stakeable.length === 0 && (
            <p className="empty-text">No NFTs available to stake.</p>
          )}
          <div className="staking-list">
            {stakeable.map((nft) => (
              <div key={nft.id} className="staking-row">
                <div>
                  <div className="staking-title">{nft.name}</div>
                  <div className="staking-sub">
                    {nft.apy}% APY • Prompt: {nft.prompt}
                  </div>
                </div>
                <button
                  className="btn btn-secondary"
                  onClick={() => onToggleStake(nft.id)}
                >
                  Stake
                </button>
              </div>
            ))}
          </div>
        </div>

        <div className="page-card staking-column">
          <h3>Currently staked</h3>
          {staked.length === 0 && (
            <p className="empty-text">No active NFT stakes yet.</p>
          )}
          <div className="staking-list">
            {staked.map((nft) => (
              <div key={nft.id} className="staking-row">
                <div>
                  <div className="staking-title">{nft.name}</div>
                  <div className="staking-sub">
                    Earning {nft.apy}% APY • Prompt: {nft.prompt}
                  </div>
                </div>
                <button
                  className="btn btn-ghost"
                  onClick={() => onToggleStake(nft.id)}
                >
                  Unstake
                </button>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

// ---- PAGE: HISTORY ----

function HistoryPage({ history }) {
  return (
    <div className="page">
      <div className="page-header">
        <h2>Transaction history</h2>
        <p>
          All activity executed by you or your AI agent. Read-only, pulled from
          Sui / explorer / your backend.
        </p>
      </div>
      <div className="page-card">
        <table className="table">
          <thead>
            <tr>
              <th>Tx ID</th>
              <th>Type</th>
              <th>Asset</th>
              <th>Amount</th>
              <th>Status</th>
              <th>Time</th>
              <th>Prompt</th>
            </tr>
          </thead>
          <tbody>
            {history.map((tx) => (
              <tr key={tx.id}>
                <td className="mono">{tx.id}</td>
                <td>{tx.type}</td>
                <td>{tx.asset}</td>
                <td>{tx.amount}</td>
                <td>
                  <span
                    className={
                      "badge " +
                      (tx.status === "Success"
                        ? "badge-success"
                        : tx.status === "Pending"
                        ? "badge-warning"
                        : "badge-danger")
                    }
                  >
                    {tx.status}
                  </span>
                </td>
                <td className="mono">{tx.time}</td>
                <td className="history-prompt">
                  {tx.promptSummary}
                  {tx.viaAgent && (
                    <span className="badge badge-outline">
                      via AI Agent
                    </span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// ---- PAGE: WALLET ----

function WalletPage({ wallet, coins }) {
  return (
    <div className="page">
      <div className="page-header">
        <h2>Wallet overview</h2>
        <p>
          Data here will come from Slash wallet / Sui wallet adapter. This is a
          read-only overview for your agent.
        </p>
      </div>
      <div className="wallet-layout">
        <div className="page-card wallet-card">
          <h3>Address</h3>
          {wallet.connected ? (
            <>
              <p className="mono wallet-address-big">
                {wallet.address}
              </p>
              <p className="wallet-balance-big">
                {wallet.suiBalance.toFixed(2)} SUI
              </p>
              <p className="helper-text">
                You can fetch this from Sui RPC / explorer or Slash wallet SDK.
              </p>
            </>
          ) : (
            <p className="empty-text">
              Wallet not connected. Use the button in the top-right.
            </p>
          )}
        </div>

        <div className="page-card wallet-card">
          <h3>Token balances (mock)</h3>
          <table className="table">
            <thead>
              <tr>
                <th>Asset</th>
                <th>Est. balance</th>
                <th>Value (approx)</th>
              </tr>
            </thead>
            <tbody>
              {coins.map((coin) => (
                <tr key={coin.symbol}>
                  <td>
                    <div className="table-asset">
                      <div className="coin-avatar small">
                        {coin.symbol[0]}
                      </div>
                      <span>
                        {coin.name} ({coin.symbol})
                      </span>
                    </div>
                  </td>
                  <td>—</td>
                  <td>${coin.price.toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <p className="helper-text">
            Replace this table with real balances from Slash / Sui RPC.
          </p>
        </div>
      </div>
    </div>
  );
}

export default App;
